# Generated by Django 3.1.3 on 2024-03-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='predicted_image',
            field=models.ImageField(blank=True, null=True, upload_to='images_predict/'),
        ),
        migrations.AddField(
            model_name='question',
            name='upload_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
