# Generated by Django 3.1.3 on 2024-04-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowds', '0002_auto_20240328_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='modify_date',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='voter',
        ),
        migrations.RemoveField(
            model_name='question',
            name='modify_date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='voter',
        ),
        migrations.AlterField(
            model_name='answer',
            name='predicted_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='upload_image',
            field=models.ImageField(blank=True, null=True, upload_to='question/%Y%m%d'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
